---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nodejs
  template:
    metadata:
      labels:
        app: hello-nodejs
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: hello-nodejs
          image: hello-nodejs
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 3000
              name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: hello-nodejs
  labels:
    app: hello-nodejs
spec:
  selector:
    app: hello-nodejs
  ports:
    - protocol: TCP
      port: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-nodejs
  annotations:
    kubernetes.io/ingress.class: shared
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    external-dns.alpha.kubernetes.io/target: traefik.codemowers.ee
spec:
  rules:
    - host: hello-nodejs-3nk45yqd6e.codemowers.ee
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: hello-nodejs
                port:
                  number: 3000
  tls:
    - hosts:
        - "*.codemowers.ee"
