apiVersion: skaffold/v3
kind: Config
metadata:
  name: hello-nodejs

manifests:
  rawYaml:
     - deployment.yaml

deploy:
  kubectl: {}

build:
  artifacts:
  - image: hello-nodejs
    #docker:
    #  target: dev
    sync:
      manual:
        - src: '*.js'
          dest: .
    # Comment following lines below to build locally
    # Note you also need to fetch Docker registry credentials
    # by following instructions provided at dashboard.codemowers.eu
  cluster:
    dockerConfig:
      secretName: kaniko

portForward:
  - resourceType: deployment
    resourceName: hello-nodejs
    port: 3000 # Express.js server itself
    localPort: 3000
  - resourceType: deployment
    resourceName: hello-nodejs
    port: 9229 # Debug port
    localPort: 9229
